language: generic
sudo: required
services:
  - docker
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: AEEexZW7I1okYStf36Al+iE6QGZTDDYklOg/+CQGAHs13zSggDHDRV0ayg2OgYkmi+VjGYjNQYTKKrGQrvz3OsA+1doaY/LRAb5paNRo3mCTgCafL16lyc6ttuqPPsg6DB2uVqfBhZBRUhK/tND053pvupT4AVPar3khFlsOxvuT0NVenfAxkT+ATEfMb1cHnjFA9WyabYWinD4IX7O22IM5+Dj6ep9XnaspkI96PDzH3jY3DC992LB7GfUHKPJk3Ms69+luV4mS/hXPRti6Iwwgcvx00A1MbEH8sSRV5gPdEXC2/3CbamIFfjpGZDOu9AGzdUUi/ZgzsQtEpi74tA+dRseE4QiLUiVgqGzTT3qvz4ef6aRHpdz5trHSpRJpw8W8Mj+vU+f7tXi0GZ4tuoKGl389/CmeNps/qq2OUn5kMEnvC6EnVF488ocQqIDU+8UeO+94cQ41ILrWxTb4keJzTrmw0+UNWeXmdOHv3opuefdmt4D1ZKHLbv76h8LGM3OyqZSlvGGql3/f7+BoNdZhmRrWY/Qyxmtxg+yfvI4TmgcqW057b9OjwvY7dp3OC9TzpYqxDNmWe1hoUucnxUsCmzAr93AjwcMFkIxgkvHroMxcabCfihTV+Iv3Zqq5YrVBXVENUPFhVQ16Mh2j4Dzv3CFXzdPQGeMnhlTA6II=
    # AWS_SECRET_ACCESS_KEY
    - secure: dcMLnuy+3tosR1TbjI+dEuhzaxETJHViMTmsJuaWMLa+B1+lQRmpwDDg9A1rLj/DHmxf6f/a8yz0sY8t8kAaofir4/I0TVv7g8T10mF4GIY4ZJ7bScqhRvPki2oT/rE35yfh1VjiFGsZLxmlWobGfLi3onCn+TnbjZgwSt1jjpedaxElaj3uAAAEdLUOeMUY3GF6c8ku7dl9B/VUugJR1KaKEpfZa7cmoJHIZnuowxGrd4sajug88lImD4Y0joZvEnoSbIU2E8n1PZgj1gp4hc1MBnTkn1QSvnOjlLdBAlKKH8SD9CI7eLUJeyOSq09dg/Vt1eo08IgoDrLahR0IV3K4ZcMsecTp8MyYXHk4aLqzC3sN6MHp0uUB8WNXad1K2RaqmGT5HB2tKlhfamV6FyCiyA0oNazgLg5WXUI3MHZCcXxXr3M1+R/eo0liH2zh07p8IQdZ33pt3SohoVXNQ+EVEvM0Alk6EJclV2bAr/MY2oriH+B308ONRA1H92SZlF7/XKwApR3B2+8SXL0UwnMRDobnU8QSTpugHc7Oj8xCRpSCY7YIWeM2rsIpomzxYbRSyxaPe7YQWP346nKeB9nCLkQNLcxWsAX9bIDILDS1mmt4wNETkBVX6HZhr/ADzJRHZBXxLrEVFLpwK7pbq3QmntiR9Np1XndqrNp7Ieo=

script:
  - make build
  - make deploy
