language: generic
sudo: required
services:
  - docker
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "vfNlFVk4ug6aPsQ+5inmSfKZ+PbW9AWLcQ+TcFsVbSunXKppyRCjrVNvbmhVGOZustwDOwlucDO56BYLgCqqyMA3Z8sx4ruF2m/ne3bZDLx7dZ1o+Pt/AXR65s83hrNgRLB+EpMFGgyAWvULGxMRSBsNOt+kspW8EbZrr8gvfMjicEj1fXzM6dRnkVjAa4bhZSvdjGqQ5/FcxRKTMZ7qh+brfjZeTTWIYVdNvT/V4yDdJwArfmLdDXGq4RKkwt1TxorOXvLDzCav5iZr3X+SYaYMfKkudYKqQXiM8akxbYN0r/OdTFzZ29gGvSxaXdxXsL32I6+gvFlNl0A8RsBqV9w4QrTpoHPw+ROXtMknx74YRq9a1pb6I6bTGUdVFgaMUodkho725T3GTRSuEuXIu2/Ytx8TkiAJq8CLyjqKkjVgJ1iKnn3EfsTsOJZbIQ+dMXuNLa7fFY/IbNaVwwfnfTJja/EzKobD6rHot20aIf3bfgK67zflVbsQFcCDuer/Jmh9/hPV6GnOJx8XvUHea1vWGXubpEcRmLhAJ9JB8dqsHy13PvxIstz99IW93fYc8yr934zvUQ+Sf9QuCx9i/ReQ+QqR1p0NscDWWuJ4IlnCj8SmF1tFCYPulSUZvkTd+dOA5kz8L/OeKsuWqZrACfDMZpEmmjNONIuLiuQJ9kU="
    # AWS_SECRET_ACCESS_KEY
    - secure: "nc9ElFt8VufaDZ3kRutoTrNoYEtTm4MQi0OE+LRgVMoFvBowUwLM6/YjHNJToN9tN4vgIQaZsmWFa160Th6GBC0r3ZUOMDJ5WwuyPHdpDaS2AAvmm8C4twOerZr4F0Ke7YUAvQksoAkRoksu7aMGOIMNJ9MDHf153UlbkYBwv737JNsiYwxsz0+rUFOI6haOOfgSeL8cubabDe+ML3hmOo3/fKCdIRvaP9Nqkkt4FDipfbAYAzcG+vCvPTitUu8Ay4gFXJSQhDyPzBSJGJ3W8VWle6Zk7LwFpyMxqzoV8RHwi4T94l2rGoLKPC84jDHENqXVv7bAkhjUs9icaqtpIRlWThs+d1xU6FwGPgmKjgNDlKgfqRbgh+jR1WBD58ha44tRZNuKdqEl+7XBc6JR+16zcRAF+ZxvYBnb0PJa1Jj+F+tmuZk1cEhgGqM1JtmLySifYjqGR0Tti5F5gHybk3wESTHnQMV8eZlp1jnfQxVAh338733FL75DCqajiftsBu9pk+45LRsGV+aXhDg1oVUL1w6l3vOBzH8lFSwiU5lBL+QqLlCF5rFNaOZpEUM1jkYTD1TU0kFZHhU20wmI9aQeIjChioRUxic3amgb0/Poaj9tR3QIDP7b7zEGbXweSPbv9qNq8dCVq+/P+wOF1i4p4l5Kbzj8YLIsQB8qf5k="

script:
  - make build
  - make deploy
