sudo: required
services:
- docker
addons:
  apt:
    packages:
    - python3
    - python3-pip
before_install:
- sudo pip3 install --upgrade pip
- sudo pip3 install --upgrade 'invoke-tools==0.2.0'
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: E3XEadAqW9J5xdzzvgyrlD6uhg3/EPuz4ZppDOCRtruPCNapdWnQH1MAkv2lIrdo6zFzqlnyejTLYH/46ahe1aeTNaFZnR23xetIEEWQBV8y72q9AntSwUtYMaQtkWGu9MsYkeHTcYPIfFhxcFJyLsK7+6KnU9VqqJR3j9HegjVbG1EKhP/+Mlrf8k2ML6Vz1Bb9KYFQ9ta/FiE5DuUwd7VMZBG9uJHnLKrguC2E9pM28fC+w/n4r95FLaIlIKnG4sPv6Q5dHs6Sq7ywUbZ94pqTK5k9Ev+8E5Mh4M4YLDuePtoXrdj2kbu51jKKadhHhKIlrNZt9cS8ZnXeXEG4gtjIayX0bQC6bgc3dRPINSLBtpFGIgvKM2di3UjdfZki1Isna0C1N5dqOyNykTL/tGLzby98WQO6BCEBZjxaBlmK6pqpnxlL3/jlgokrGacXPrA7RzLiiBIZlRjHDWAOs/wIAQ8gVBRnfzlXwDgCNfUfsJue2gaoAzwk6rG3nHh8d80tv10YPU1bCjnBEhtUuwurudDHLjTXwGCa3T4XcyAZd8OxEKXE+WuetZpqAhnzYmD5KYFuuRzriqbGBV9DUywpgTeunOae5zRv3wi6UsaD1tjLvsGuSSpwMEZBcKsO4ezBrRARn8kAO+iNmDCr1wkZfy/XFmu/RAzuvMpQ5g8=
    # AWS_SECRET_ACCESS_KEY
    - secure: ltg542orqXh/GawbQ0w/yHO85Ympi2Kl4eRg5Xok+Ikx3zwVLHZTZRNdifkyG4mIwiwsIZIGDe0NtZoOc7PQjacUcQHl+f3ydC0n/Lk1bIK9K8QN0RxQyBcGFAvLEp4CYgc9EK0zjigZc47O84qTqgZnl2p7k3I6XAFtIQm4Wm9WmtiZ9MB+JVpJptZs8oGqLhKUfP43qoYw3+Ly2bSf7DUCHg+RvPts5TrM7XR0uV43ZeMyBC5JMg/sxiWWrbS+Urii+VudL1/jknR5VNgKx5XRnm8Iet1Vjq7JCRJ5X1VfGvHe/wkN2UoMjcFh4zR6igy2JyekhylFyksXhNNn9n7O3uB0fInxqLnQr9RZf9LLrQr10D/pqVQ+0ubwXblpL/27Fsnb8tv4Jwt3sdu07lsuljW6RwGd/MVx2PtXCQXPzWk4G5loCp/7UEzhYH5A1IZNztrlavqpvmvd+Pomau+Vn/dqgj7Rt6EcfxeKCX6WVoAmNKfWsF1yEy+Gb53Y/83c+ZW7c3p7YOWnCJfWyDbGWsQE7sUq43o1vcKDCM8kGGWzGqm/cCpT/M0Ug36ogM+WEpDvxcp7aYKkxncB4yj/HjEyQEh0K4lDSDvPn9IZmlJ4W7usQv4wH2FewQlKl+Dgq6ozAKdynpoZhhiaBMvAO09JTKVQwAb45ePKhS8=
script:
  - invoke build
  - invoke deploy
