baseurl = "https://vjpatel.me"
title = "VJ Patel"
languageCode = "en-gb"

[params]
  email_address = "vj@vjpatel.me"
  location = "London/Reading"
  github_username = "VJftw"
  twitter_username = "VJftw"
  linkedin_url = "https://uk.linkedin.com/pub/vj-patel/6b/648/109"

[params.meta]
  description = ""
  keywords = ""

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
